/**
 * Brand mark — the four-blade X (public/brand/*, regenerated by `npm run gen:logo`).
 * The art is near-black, so on dark surfaces pair it with `glow` (default), which
 * rims the silhouette in ink-toned light. Decorative: hidden from the a11y tree —
 * give the surrounding link/heading its own label.
 */
export default function LogoMark({
  size = 22,
  glow = true,
  className = "",
}: {
  size?: number;
  glow?: boolean;
  className?: string;
}) {
  return (
    // eslint-disable-next-line @next/next/no-img-element -- static brand asset, no optimization needed
    <img
      src={size > 48 ? "/brand/mark.png" : "/brand/mark-96.png"}
      width={size}
      height={size}
      alt=""
      aria-hidden="true"
      draggable={false}
      className={`${glow ? "mark-glow " : ""}shrink-0 select-none ${className}`}
    />
  );
}
