/* ============================================================================
 * Salience baseline — a measurement instrument, not a screen.
 *
 * The list below is what the discovery-stage model tier (Sonnet) produces when
 * asked, with NO tools and NO web access, to list the ~200 US-listed tickers
 * most associated with "next mega-cap / next Nvidia / next Tesla" narratives
 * in financial media and retail social feeds, ordered by how salient they feel
 * — i.e. it is a direct capture of the model's TRAINING-DATA prior, which is
 * itself distilled media coverage. A delivered pick appearing high on this
 * list is evidence the pick came from name familiarity rather than from data.
 *
 * Used by scripts/audit-salience.ts to measure, per run, how much of the
 * delivered cohort sits inside the model's own memory of famous names, vs the
 * expected overlap if picks were drawn at random from the eligible universe.
 *
 * Instrument: one tool-less Sonnet session (cold memory), 2026-07-16.
 * Refresh cadence: regenerate roughly quarterly, or after a discovery-model
 * change — the prior moves with the model, not with the news cycle.
 * Server/script-side only; never imported by client code or shown publicly.
 * ========================================================================== */

export interface SalienceEntry {
  t: string;
  n: string;
}

export const SALIENCE_BASELINE_DATE = "2026-07-16";
export const SALIENCE_BASELINE_INSTRUMENT =
  "tool-less Sonnet session, cold memory, ordered by salience (most-mentioned first)";

export const SALIENCE_BASELINE: SalienceEntry[] = [
  { t: "SOFI", n: "SoFi Technologies, Inc." },
  { t: "RIVN", n: "Rivian Automotive, Inc." },
  { t: "LCID", n: "Lucid Group, Inc." },
  { t: "SMCI", n: "Super Micro Computer, Inc." },
  { t: "SOUN", n: "SoundHound AI, Inc." },
  { t: "HOOD", n: "Robinhood Markets, Inc." },
  { t: "IONQ", n: "IonQ, Inc." },
  { t: "RKLB", n: "Rocket Lab USA, Inc." },
  { t: "NIO", n: "NIO Inc." },
  { t: "SPCE", n: "Virgin Galactic Holdings, Inc." },
  { t: "MARA", n: "MARA Holdings, Inc." },
  { t: "RIOT", n: "Riot Platforms, Inc." },
  { t: "MSTR", n: "MicroStrategy Incorporated" },
  { t: "COIN", n: "Coinbase Global, Inc." },
  { t: "QS", n: "QuantumScape Corporation" },
  { t: "PLUG", n: "Plug Power Inc." },
  { t: "ACHR", n: "Archer Aviation Inc." },
  { t: "JOBY", n: "Joby Aviation, Inc." },
  { t: "ASTS", n: "AST SpaceMobile, Inc." },
  { t: "QUBT", n: "Quantum Computing Inc." },
  { t: "RGTI", n: "Rigetti Computing, Inc." },
  { t: "QBTS", n: "D-Wave Quantum Inc." },
  { t: "NVAX", n: "Novavax, Inc." },
  { t: "MVIS", n: "MicroVision, Inc." },
  { t: "NKLA", n: "Nikola Corporation" },
  { t: "OKLO", n: "Oklo Inc." },
  { t: "SMR", n: "NuScale Power Corporation" },
  { t: "CRWV", n: "CoreWeave, Inc." },
  { t: "BBAI", n: "BigBear.ai Holdings, Inc." },
  { t: "AI", n: "C3.ai, Inc." },
  { t: "UPST", n: "Upstart Holdings, Inc." },
  { t: "ARM", n: "Arm Holdings plc" },
  { t: "WKHS", n: "Workhorse Group Inc." },
  { t: "GOEV", n: "Canoo Inc." },
  { t: "AFRM", n: "Affirm Holdings, Inc." },
  { t: "NU", n: "Nu Holdings Ltd." },
  { t: "VKTX", n: "Viking Therapeutics, Inc." },
  { t: "CRSP", n: "CRISPR Therapeutics AG" },
  { t: "LAZR", n: "Luminar Technologies, Inc." },
  { t: "XPEV", n: "XPeng Inc." },
  { t: "LI", n: "Li Auto Inc." },
  { t: "DNA", n: "Ginkgo Bioworks Holdings, Inc." },
  { t: "RXRX", n: "Recursion Pharmaceuticals, Inc." },
  { t: "FFIE", n: "Faraday Future Intelligent Electric Inc." },
  { t: "VFS", n: "VinFast Auto Ltd." },
  { t: "PSNY", n: "Polestar Automotive Holding UK PLC" },
  { t: "CHPT", n: "ChargePoint Holdings, Inc." },
  { t: "NNE", n: "NANO Nuclear Energy Inc." },
  { t: "CCJ", n: "Cameco Corporation" },
  { t: "UEC", n: "Uranium Energy Corp." },
  { t: "UUUU", n: "Energy Fuels Inc." },
  { t: "LEU", n: "Centrus Energy Corp." },
  { t: "CEG", n: "Constellation Energy Corporation" },
  { t: "VST", n: "Vistra Corp." },
  { t: "TLN", n: "Talen Energy Corporation" },
  { t: "GEV", n: "GE Vernova Inc." },
  { t: "VRT", n: "Vertiv Holdings Co" },
  { t: "ANET", n: "Arista Networks, Inc." },
  { t: "DELL", n: "Dell Technologies Inc." },
  { t: "CRDO", n: "Credo Technology Group Holding Ltd" },
  { t: "ALAB", n: "Astera Labs, Inc." },
  { t: "NBIS", n: "Nebius Group N.V." },
  { t: "APLD", n: "Applied Digital Corporation" },
  { t: "IREN", n: "IREN Limited" },
  { t: "CORZ", n: "Core Scientific, Inc." },
  { t: "WULF", n: "TeraWulf Inc." },
  { t: "CIFR", n: "Cipher Mining Inc." },
  { t: "HUT", n: "Hut 8 Corp." },
  { t: "CLSK", n: "CleanSpark, Inc." },
  { t: "BITF", n: "Bitfarms Ltd." },
  { t: "BTBT", n: "Bit Digital, Inc." },
  { t: "CRCL", n: "Circle Internet Group, Inc." },
  { t: "SBET", n: "SharpLink Gaming, Inc." },
  { t: "BMNR", n: "Bitmine Immersion Technologies, Inc." },
  { t: "OPEN", n: "Opendoor Technologies Inc." },
  { t: "RDDT", n: "Reddit, Inc." },
  { t: "APP", n: "AppLovin Corporation" },
  { t: "TEM", n: "Tempus AI, Inc." },
  { t: "RBRK", n: "Rubrik, Inc." },
  { t: "IOT", n: "Samsara Inc." },
  { t: "KVYO", n: "Klaviyo, Inc." },
  { t: "CART", n: "Maplebear Inc." },
  { t: "FIG", n: "Figma, Inc." },
  { t: "GRAB", n: "Grab Holdings Limited" },
  { t: "HIMS", n: "Hims & Hers Health, Inc." },
  { t: "OSCR", n: "Oscar Health, Inc." },
  { t: "CLOV", n: "Clover Health Investments, Corp." },
  { t: "DAVE", n: "Dave Inc." },
  { t: "MQ", n: "Marqeta, Inc." },
  { t: "FOUR", n: "Shift4 Payments, Inc." },
  { t: "BILL", n: "Bill.com Holdings, Inc." },
  { t: "LC", n: "LendingClub Corporation" },
  { t: "PATH", n: "UiPath Inc." },
  { t: "SNOW", n: "Snowflake Inc." },
  { t: "DDOG", n: "Datadog, Inc." },
  { t: "CRWD", n: "CrowdStrike Holdings, Inc." },
  { t: "NET", n: "Cloudflare, Inc." },
  { t: "S", n: "SentinelOne, Inc." },
  { t: "ZS", n: "Zscaler, Inc." },
  { t: "GTLB", n: "GitLab Inc." },
  { t: "CFLT", n: "Confluent, Inc." },
  { t: "ESTC", n: "Elastic N.V." },
  { t: "EVLV", n: "Evolv Technologies Holdings, Inc." },
  { t: "MRVL", n: "Marvell Technology, Inc." },
  { t: "AMD", n: "Advanced Micro Devices, Inc." },
  { t: "WOLF", n: "Wolfspeed, Inc." },
  { t: "ON", n: "ON Semiconductor Corporation" },
  { t: "LSCC", n: "Lattice Semiconductor Corporation" },
  { t: "SITM", n: "SiTime Corporation" },
  { t: "AMBA", n: "Ambarella, Inc." },
  { t: "SGH", n: "SMART Global Holdings, Inc." },
  { t: "COHR", n: "Coherent Corp." },
  { t: "LITE", n: "Lumentum Holdings Inc." },
  { t: "FN", n: "Fabrinet" },
  { t: "AAOI", n: "Applied Optoelectronics, Inc." },
  { t: "MP", n: "MP Materials Corp." },
  { t: "NTLA", n: "Intellia Therapeutics, Inc." },
  { t: "BEAM", n: "Beam Therapeutics Inc." },
  { t: "EDIT", n: "Editas Medicine, Inc." },
  { t: "VERV", n: "Verve Therapeutics, Inc." },
  { t: "ARWR", n: "Arrowhead Pharmaceuticals, Inc." },
  { t: "SANA", n: "Sana Biotechnology, Inc." },
  { t: "ABCL", n: "AbCellera Biologics Inc." },
  { t: "SDGR", n: "Schrodinger, Inc." },
  { t: "TXG", n: "10x Genomics, Inc." },
  { t: "PACB", n: "Pacific Biosciences of California, Inc." },
  { t: "IOVA", n: "Iovance Biotherapeutics, Inc." },
  { t: "RCKT", n: "Rocket Pharmaceuticals, Inc." },
  { t: "ALT", n: "Altimmune, Inc." },
  { t: "TDOC", n: "Teladoc Health, Inc." },
  { t: "EXAS", n: "Exact Sciences Corporation" },
  { t: "GH", n: "Guardant Health, Inc." },
  { t: "ENVX", n: "Enovix Corporation" },
  { t: "SES", n: "SES AI Corporation" },
  { t: "FREY", n: "FREYR Battery, Inc." },
  { t: "AMPX", n: "Amprius Technologies, Inc." },
  { t: "STEM", n: "Stem, Inc." },
  { t: "BE", n: "Bloom Energy Corporation" },
  { t: "FCEL", n: "FuelCell Energy, Inc." },
  { t: "BLDP", n: "Ballard Power Systems Inc." },
  { t: "HYLN", n: "Hyliion Holdings Corp." },
  { t: "EVGO", n: "EVgo Inc." },
  { t: "BLNK", n: "Blink Charging Co." },
  { t: "AEVA", n: "Aeva Technologies, Inc." },
  { t: "OUST", n: "Ouster, Inc." },
  { t: "INVZ", n: "Innoviz Technologies Ltd." },
  { t: "MBLY", n: "Mobileye Global Inc." },
  { t: "AUR", n: "Aurora Innovation, Inc." },
  { t: "WRD", n: "WeRide Inc." },
  { t: "PONY", n: "Pony AI Inc." },
  { t: "KTOS", n: "Kratos Defense & Security Solutions, Inc." },
  { t: "AVAV", n: "AeroVironment, Inc." },
  { t: "RCAT", n: "Red Cat Holdings, Inc." },
  { t: "ONDS", n: "Ondas Holdings Inc." },
  { t: "UMAC", n: "Unusual Machines, Inc." },
  { t: "AXON", n: "Axon Enterprise, Inc." },
  { t: "DRS", n: "Leonardo DRS, Inc." },
  { t: "EH", n: "EHang Holdings Limited" },
  { t: "EVEX", n: "Eve Holding, Inc." },
  { t: "BLDE", n: "Blade Air Mobility, Inc." },
  { t: "LUNR", n: "Intuitive Machines, Inc." },
  { t: "RDW", n: "Redwire Corporation" },
  { t: "BKSY", n: "BlackSky Technology Inc." },
  { t: "PL", n: "Planet Labs PBC" },
  { t: "MNTS", n: "Momentus Inc." },
  { t: "SIDU", n: "Sidus Space, Inc." },
  { t: "GSAT", n: "Globalstar, Inc." },
  { t: "IRDM", n: "Iridium Communications Inc." },
  { t: "VSAT", n: "Viasat, Inc." },
  { t: "KULR", n: "KULR Technology Group, Inc." },
  { t: "SERV", n: "Serve Robotics Inc." },
  { t: "RR", n: "Richtech Robotics Inc." },
  { t: "ARQQ", n: "Arqit Quantum Inc." },
  { t: "LAES", n: "SEALSQ Corp" },
  { t: "BWXT", n: "BWX Technologies, Inc." },
  { t: "DNN", n: "Denison Mines Corp." },
  { t: "LTBR", n: "Lightbridge Corporation" },
  { t: "RBLX", n: "Roblox Corporation" },
  { t: "U", n: "Unity Software Inc." },
  { t: "DUOL", n: "Duolingo, Inc." },
  { t: "SQ", n: "Block, Inc." },
  { t: "SHOP", n: "Shopify Inc." },
  { t: "ROKU", n: "Roku, Inc." },
  { t: "ENPH", n: "Enphase Energy, Inc." },
  { t: "FSLR", n: "First Solar, Inc." },
  { t: "RUN", n: "Sunrun Inc." },
  { t: "SEDG", n: "SolarEdge Technologies, Inc." },
  { t: "GDS", n: "GDS Holdings Limited" },
  { t: "VNET", n: "VNET Group, Inc." },
  { t: "DBRG", n: "DigitalBridge Group, Inc." },
  { t: "NRG", n: "NRG Energy, Inc." },
  { t: "SLNH", n: "Soluna Holdings, Inc." },
  { t: "GREE", n: "Greenidge Generation Holdings Inc." },
  { t: "TTD", n: "The Trade Desk, Inc." },
  { t: "MDB", n: "MongoDB, Inc." },
  { t: "PSTG", n: "Pure Storage, Inc." },
  { t: "POET", n: "POET Technologies Inc." },
  { t: "TMC", n: "TMC the metals company inc." },
  { t: "GEMI", n: "Gemini Space Station, Inc." },
  { t: "BLSH", n: "Bullish" },
];

const rankByTicker = new Map(SALIENCE_BASELINE.map((e, i) => [e.t, i + 1]));

/** 1-based salience rank (1 = most salient), or null when the ticker is not in the baseline. */
export function salienceRank(ticker: string): number | null {
  return rankByTicker.get(ticker.toUpperCase()) ?? null;
}
